src/main/resources/application.yaml
=> Added swagger URL

build.gradle
added 
mainClassName = 'uk.gov.hmcts.reform.roleassignment.Application'
to the build.gradle
=> fix bootRun

src/main/java/uk/gov/hmcts/reform/roleassignment/config/AppInsights.java, src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/AM-738
Fix the master pipeline.
```
[ ] Yes
[ ] No
```
=> PR Branch: master branch fix.

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/AM-751
=> AM-751 nightly pipeline implementation

src/main/resources/application.yaml, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
=> PR Branch: Updating smoke test.

charts/am-role-assignment-service/Chart.yaml
=> PR Branch: Helm upgrade.

charts/am-role-assignment-service/values.yaml
=> AM-738: values.yml updates.

Jenkinsfile_CNP
=> AM-738: Disabling the Jenkins goal "installCharts()".

src/main/java/uk/gov/hmcts/reform/roleassignment/config/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/WelcomeController.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-736
Implement S2S and User Token based security
```
[ ] Yes
[ x] No
```
=> Am 736 s2 s implementation

Jenkinsfile_CNP
=> AM-738: Bumping the chart version.

charts/am-role-assignment-service/values.preview.template.yaml, docker-compose.yml, src/main/resources/application.yaml, src/main/resources/bootstrap.yml, src/main/resources/db/changelog/db.changelog-master.xml
=> AM-764: Fixing the docker image issues.

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/WelcomeControllerIntegrationTest.java
=> AM-764: Disabling the Integration test.

charts/am-role-assignment-service/requirements.yaml
=> Bumping the Java image version.

src/main/resources/bootstrap.yml
=> Fixing the space issues.

.travis.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
https://tools.hmcts.net/jira/browse/AM-797
java version upgrade
```
[ ] Yes
[x] No
```
=> java version upgrade

src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
https://tools.hmcts.net/jira/browse/AM-828
=> AM-828 - fixed 500 error, throws 400 now.

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
https://tools.hmcts.net/jira/browse/AM-828
=> AM-828_further_fixes

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Case.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/feignclients/configuration/DatastoreFeignClientFallback.java, src/main/resources/META-INF/kmodule.xml, src/main/resources/application.yaml, src/main/resources/validationrules/case.drl, src/main/resources/validationrules/request.drl, src/main/resources/validationrules/requestedRole.drl, src/main/resources/validationrules/role.drl
https://tools.hmcts.net/jira/browse/AM-826
Modify drool rules for delete functionality
```
[ ] Yes
[ x] No
```
=> AM-826 : modified drool rules.

src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java
https://tools.hmcts.net/jira/browse/AM-831
=> AM-831 validation for caseID

src/test/resources/attributes.json
=> fixed missing attribute issue

src/functionalTest/resources/features/F-000/S-000.td.json, src/functionalTest/resources/features/F-001/F-001.feature
F001 Fix
```
[ ] Yes
[x] No
```
=> Response mismatch fix

build.gradle
=> Dummy checkin

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/exception/ResourceNotFoundException.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/roleassignment/HistoryRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/roleassignment/RoleAssignmentRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java, src/main/resources/validationrules/request.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java
https://tools.hmcts.net/jira/browse/AM-840
Development of Delete role assignments by actor id or process/reference
```
[ ] Yes
[x ] No
```
=> Am 840 delete api

src/main/java/uk/gov/hmcts/reform/roleassignment/data/roleassignment/HistoryRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/main/resources/validationrules/request.drl, src/main/resources/validationrules/requestedRole.drl
https://tools.hmcts.net/jira/browse/AM-865
https://tools.hmcts.net/jira/browse/AM-864
Log is not generated for Multiple Role Assignment Rejected Status
ReplaceExisting is True without Process and Reference payload is Accepted
```
[ ] Yes
[ x] No
```
=> Am 864 replace existing true

src/functionalTest/resources/features/F-007/F-007.feature, src/main/java/uk/gov/hmcts/reform/roleassignment/apihelper/Constants.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java, src/test/resources/role.json
https://tools.hmcts.net/jira/browse/AM-794
=> AM-806 - get list of roles endpoint

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/ErrorConstants.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java
https://tools.hmcts.net/jira/browse/AM-869
https://tools.hmcts.net/jira/browse/AM-870
https://tools.hmcts.net/jira/browse/AM-868
https://tools.hmcts.net/jira/browse/AM-871
Reference is wrongly updated in Request Table when failed to delete a record
Role Assignments deleted with wrong Correlation Id and Assigner Id values
Error code should be 404 for wrong Actor ID, process and reference of Delete API
Swagger UI is not working for Delete API
```
[ ] Yes
[ x] No
```
=> AM-871 : fixed swagger issue along with other defects(AM-869,AM-868).

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java
AM-872: Swagger UI is not working for Get Role Assignment by Actor Id
AM-873: Error Code should be 404 for wrong Actor Id of GET API
Bug fixes
```
[ ] Yes
[x ] No
```
=> Get API Swagger/404 issue fix

Jenkinsfile_CNP, src/functionalTest/resources/features/F-007/F-007-Base-Root.td.json, src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-007/F-007_Test_Data_Base.td.json, src/functionalTest/resources/features/F-007/S-071.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java
AM-811
Test data for functional testing of Get Static Role API
```
[ ] Yes
[x] No
```
=> Am 811 functional test cases

charts/am-role-assignment-service/Chart.yaml
https://tools.hmcts.net/jira/browse/AM-877
```
[ ] Yes
[X] No
```
=> Update chart version

src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
=> AAT- Fixing the Smoke test issue.

src/functionalTest/resources/features/F-002/F-002-Base-Root.td.json, src/functionalTest/resources/features/F-002/F-002.feature, src/functionalTest/resources/features/F-002/F-002_Test_Data_Base.td.json, src/functionalTest/resources/features/F-002/S-021.td.json, src/functionalTest/resources/features/F-002/S-021_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-002/S-022.td.json, src/functionalTest/resources/features/F-002/S-022_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-002/S-023.td.json, src/functionalTest/resources/features/F-002/S-024.td.json, src/functionalTest/resources/features/F-002/S-025.td.json, src/functionalTest/resources/features/F-002/S-025_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-002/S-026.td.json, src/functionalTest/resources/features/F-002/S-026_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-002/S-027.td.json, src/functionalTest/resources/features/F-002/S-028.td.json, src/functionalTest/resources/features/F-002/S-029.td.json, src/functionalTest/resources/features/F-002/S-030.td.json, src/functionalTest/resources/features/F-002/S-030_DeleteDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-005/S-052_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-005/S-053.td.json, src/functionalTest/resources/features/F-005/S-055.td.json, src/functionalTest/resources/features/F-005/S-058.td.json
=> Am 845 delete assignments functional tests

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
https://tools.hmcts.net/jira/browse/AM-763
AM-763: Delete by assignment Id. Adding Junits.
```
[ ] Yes
[x] No
```
=> AM-763: Delete by assignment Id. Adding Junits.

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
=> AM-763: Delete by assignment Id. Fixing the broken functional tests.

src/functionalTest/resources/features/F-003/F-003-Base-Root.td.json, src/functionalTest/resources/features/F-003/F-003.feature, src/functionalTest/resources/features/F-003/F-003_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-003/F-003_DeleteDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-003/F-003_Test_Data_Base.td.json, src/functionalTest/resources/features/F-003/S-031.td.json, src/functionalTest/resources/features/F-003/S-032.td.json, src/functionalTest/resources/features/F-003/S-033.td.json, src/functionalTest/resources/features/F-003/S-034.td.json
=> AM-875 Functional Test cases for F-003

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
AM-763
Added Junits for Delete by Assignment Id.
```
[ ] Yes
[ ] No
```
=> Am 763 delete role assignment by assignment

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/Status.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/main/resources/validationrules/case.drl, src/main/resources/validationrules/request.drl, src/main/resources/validationrules/requestedRole.drl, src/main/resources/validationrules/role.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
https://tools.hmcts.net/jira/browse/AM-863
Refine existing drool rule and add new rule, also optimize code to handle multiple scenario.
```
[ ] Yes
[ x] No
```
=> Am 863 identify delete drool rule

src/functionalTest/resources/features/F-000/F-000.feature
=> Disabling F-000.feature

src/functionalTest/resources/features/F-001/F-001-Base-Root.td.json, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/F-001_Test_Data_Base.td.json, src/functionalTest/resources/features/F-001/S-001.td.json, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-003.td.json, src/functionalTest/resources/features/F-001/S-004.td.json, src/functionalTest/resources/features/F-001/S-005.td.json, src/functionalTest/resources/features/F-001/S-006.td.json, src/functionalTest/resources/features/F-001/S-007.td.json, src/functionalTest/resources/features/F-001/S-008.td.json, src/functionalTest/resources/features/F-001/S-009.td.json, src/functionalTest/resources/features/F-001/S-010.td.json, src/functionalTest/resources/features/F-001/S-012.td.json, src/functionalTest/resources/features/F-001/S-013.td.json, src/functionalTest/resources/features/F-001/S-018.td.json, src/functionalTest/resources/features/F-001/S-019.td.json, src/functionalTest/resources/features/common/ResponseRoleRequest.td.json
https://tools.hmcts.net/jira/browse/AM-836
Functional test automation for Create Role Assignments.
[ ] Yes
[x] No
=> AM-836: Functional test automation for Create Role Assignments

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/roleassignment/RoleAssignmentRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java
AM-760
Added Junits for the Get Assignment by Actor or case id.
```
[ ] Yes
[x] No
```
=> Am 760 junits

src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java
=> AM-760: Added case insensitive role type comparison.

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java
https://tools.hmcts.net/jira/browse/AM-902
Weak Etag Support
```
[ ] Yes
[x] No
```
=> AM-902 : Weak Etag support

src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java
https://tools.hmcts.net/jira/browse/AM-920
Regression Issue: Not able to create Organisation Role Assignment without CASE ID
```
[ ] Yes
[ x] No
```
=> AM-920 : Fix for Organization.

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/integrationTest/resources/sql/insert_role_assignment_request.sql
https://tools.hmcts.net/jira/browse/AM-898
Fix IT in PR and generate report
```
[x ] Yes
[ ] No
```
=> AM-898: Fix IT in PR and generate report

build.gradle
=> Disabling sonar in master

build.gradle
Didn't work so reverting this change
=> Revert "Disabling sonar in master"

build.gradle, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/OIdcAdminConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtilsTest.java
=> AM-901 coverage

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, infrastructure/main.tf, src/main/resources/application.yaml, src/main/resources/bootstrap.yml
Am-927
LD variable creation.
```
[ ] Yes
[ ] No
```
=> AM-927: Launch Darkly initial checkin. Added the LD secrets.

src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/JwtGrantedAuthoritiesConverter.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/CreatedTimeComparatorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtilsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
https://tools.hmcts.net/jira/browse/AM-930
=> Am - 930 - Junit improvement

Dockerfile, build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/WelcomeControllerIntegrationTest.java
=> Am-940: Downgrading the JDK version.

src/functionalTest/resources/features/F-002/F-002.feature, src/functionalTest/resources/features/F-006/F-006.feature
https://tools.hmcts.net/jira/browse/AM-939
Changed Feature file name.
[ ] Yes
[x] No
=> AM-939: Feature name changes.

infrastructure/main.tf, src/main/resources/application.yaml, src/main/resources/bootstrap.yml
=> Launch darkly environment setup

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml
LD keys
```
[ ] Yes
[ ] No
```
=> AM-927: Adding env variables.

src/main/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentApplication.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/LDCacheConfig.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/LDFlagChecker.java, src/main/resources/application.yaml
AM-927
Adding Bean caching in LD.
```
[ ] Yes
[ ] No
```
=> AM-927: Adding LD Bean caching.

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluation.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggle.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/LaunchDarklyConfiguration.java
=> AM-927: Launch Darkly updates

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java
Code smell fixes.
```
[ ] Yes
[ ] No
```
=> refactor: Removing the code smells.

build.gradle
=> refactor: removing the Kotlin dependencies.

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluation.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggle.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/LaunchDarklyConfiguration.java
Disabling the feature flags. Will enable it again post unit tests.
```
[ ] Yes
[ ] No
```
=> refactor: Disabling the Launch Darkly temporarily

Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/AM-949
=> Enable notifications and func test report archiving

build.gradle
=> refactor: Fixing the integration test report.

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-016.td.json, src/functionalTest/resources/features/F-001/S-017.td.json, src/functionalTest/resources/features/F-001/S-017_Clear_Multiple_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-017_Multiple_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-018.td.json, src/functionalTest/resources/features/F-001/S-018_Multiple_Role_Creation.td.json
https://tools.hmcts.net/jira/browse/AM-956
Functional test automation for Replace existing is TRUE enhancements.
[ ] Yes
[x] No
=> AM-956 functional test automation for Replace Existing True enhancements.

Jenkinsfile_CNP, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/WelcomeControllerIntegrationTest.java, src/integrationTest/resources/serenity.properties, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
AM-975: Separate report for Integration tests.
```
[ ] Yes
[ ] No
```
=> refactor: Generating the serenity report for Integration tests.

src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java
=> refactor: Fixing the scope in OpenId.

Jenkinsfile_CNP
=> AM-975 - adding integration test report to pipeline

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentCreateAndDeleteIntegrationTest.java
https://tools.hmcts.net/jira/browse/AM-970
Integration test for delete assignments by assignment Id
[ ] Yes
[x ] No
=> AM-970: Integration test for delete assignments by assignment Id 

src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluationTest.java
Fixing the SonarLints.
```
[ ] Yes
[ ] No
```
=> AM-968: Fixed the Sonarlint issues.

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/FeatureFlagToggleEvaluator.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
=> AM-968: Fixed the Serenity Restassured issues.

build.gradle
=> Fixing the CVE issues.

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/FeatureFlagToggleEvaluator.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
=> Enabling the Launch Darkly Smoke tests.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/LaunchDarklyConfiguration.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluation.java, src/main/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggleService.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/FeatureFlagToggleEvaluator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluationTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggleServiceTest.java
AM-992: Launch Darkly fixes.
```
[ ] Yes
[ ] No
```
=> AM-992: Launch Darkly Fixes.

build.gradle
Updating the Launch Darkly jar.
```
[ ] Yes
[ ] No
```
=> Fixing the Launch Darkly jar.

Jenkinsfile_CNP, Jenkinsfile_nightly, src/main/java/uk/gov/hmcts/reform/roleassignment/config/UserTokenProviderConfig.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
https://tools.hmcts.net/jira/browse/AM-980
AM-980: Removing the secret from Jenkins file.
```
[ ] Yes
[x] No
```
=> AM-980: Removing the secret from Jenkins file.

src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditEntry.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditLogFormatter.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/LogAudit.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditAspect.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditContext.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/RoleAssignmentResource.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentControllerTest.java
https://tools.hmcts.net/jira/browse/AM-999
Missing elements in Audit log information.
```
[ ] Yes
[x ] No
```
=> Am 999 missing elements in audit log infomation

build.gradle
=> AM-992: Updating the BEFTA Jar version.

src/functionalTest/resources/features/F-000/F-000_Test_Data_Base.td.json, src/functionalTest/resources/features/F-000/S-000.td.json
=> AM-1010: Fixing the liveness probe response.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/SecurityConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1021
Enable security for Actuator Endpoint
```
[ ] Yes
[x ] No
```
=> AM-1021- Enable Security for actuator endpoint.

charts/am-role-assignment-service/Chart.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-1023
=> AM-1023 - closing input streams

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/am-role-assignment-service/Chart.yaml, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-018.td.json, src/functionalTest/resources/features/F-001/S-019.td.json, src/functionalTest/resources/features/F-002/F-002.feature, src/functionalTest/resources/features/F-002/S-030_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-006/F-006_DeleteRoleAssignmentsByActorId.td.json, src/functionalTest/resources/features/F-006/S-062_DeleteRoleAssignmentsByCaseId.td.json, src/functionalTest/resources/features/F-006/S-065_DeleteRoleAssignmentsByCaseId.td.json, src/functionalTest/resources/features/F-006/S-068.td.json
https://tools.hmcts.net/jira/browse/AM-1015
```
[ ] Yes
[x] No
```
=> AM-1015 for FTA data deletion and additional scenarios

src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/OIdcAdminConfiguration.java, src/main/resources/application.yaml, src/main/resources/liquibase.properties, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/OIdcAdminConfigurationTest.java
AM-1020
```
[ ] Yes
[ ] No
```
=> AM-1020: Updating the variable names.

src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
AM-1010
```
[ ] Yes
[x] No
```
=> AM-1010: Updated smoke test feature flag names.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentControllerTest.java
https://tools.hmcts.net/jira/browse/AM-1025
Duplicate CorrelationId in Swagger Page.
```
[ ] Yes
[X ] No
```
=> AM-1025- Fixed duplication of Correlation Id in Swagger Page.

src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java
AM-1010
```
[ ] Yes
[ ] No
```
=> AM-1010: Fixing the flag name in smoke tests.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/LiquibaseConfig.java, src/main/resources/application.yaml
AM-1043: Liquibase DB lock fix.
```
[ ] Yes
[x] No
```
=> Am master fix

src/main/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentApplication.java, src/main/java/uk/gov/hmcts/reform/roleassignment/config/LiquibaseConfig.java
AM-1043: Initialize liquibase after pod startup.
Initialize liquibase after pod startup.
```
[ ] Yes
[x] No
```
=> AM-1043: Liquibase changeloglock fix.

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java
AM-1043
Fixing the liquibase issue.
```
[ ] Yes
[ ] No
```
=> Liquibase version downgrade to stable 3.10.2

build.gradle, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java
=> disabling the idam search user functionality

src/main/java/uk/gov/hmcts/reform/roleassignment/config/LiquibaseConfig.java
AM-1043
Force releasing the locks.
```
[ ] Yes
[x] No
```
=> Liquibase force lock release

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java
AM-1066
Am perftest logging
```
[ ] Yes
[x] No
```
=> Am perftest logging

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-091.td.json, src/functionalTest/resources/features/F-001/S-092.td.json, src/functionalTest/resources/features/F-001/S-097.td.json, src/functionalTest/resources/features/F-001/S-097_Response_no_authorisations.td.json, src/functionalTest/resources/features/F-001/S-097_Single_Role_Creation.td.json
https://tools.hmcts.net/jira/browse/AM-1036
Adding new scenarios for Authorisations in F-001 feature file.
[ ] Yes
[x] No
=> AM-1036: Adding a new column in RAS - Authorisations

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-101.td.json, src/functionalTest/resources/features/F-001/S-101_Response_without_time.td.json, src/functionalTest/resources/features/F-001/S-101_Role_Request_without_time.td.json, src/functionalTest/resources/features/F-001/S-102.td.json
https://tools.hmcts.net/jira/browse/AM-1030
functional test scenarios for Assignment end time for Role Tye = ORGANISATION
[ ] Yes
[x] No
=> AM-1030: Assignment end time scenario for Role Tye = ORGANISATION

src/functionalTest/resources/features/F-006/F-006-Base-Root.td.json, src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-006/F-006_DeleteRoleAssignmentsByActorId.td.json, src/functionalTest/resources/features/F-006/F-006_Test_Data_Base.td.json, src/functionalTest/resources/features/F-006/S-061.td.json, src/functionalTest/resources/features/F-006/S-081.td.json
https://tools.hmcts.net/jira/browse/AM-1031
AM-1031: Fetch role assignments based on query request. Functional Test Automation.
[ ] Yes
[x] No
=> AM-1031: Fetch role assignments based on query request

Jenkinsfile_CNP, Jenkinsfile_nightly
=> Moving the secrets from CCD vault to AM vault.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/LiquibaseConfig.java
=> Liquibase lock release.

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/resources/validationrules/judge_validation.drl, src/main/resources/validationrules/reject.drl, src/main/resources/validationrules/stcw_validation.drl, src/main/resources/validationrules/tcw_validation.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentServiceTest.java
https://tools.hmcts.net/jira/browse/AM-1086
Drool rule update for delete API
```
[ ] Yes
[ x] No
```
=> AM-1086-  update drool rules for delete api.

build.gradle
https://tools.hmcts.net/jira/browse/AM-1090
fix pact provider issue
[ ] Yes
[ x] No
```
=> AM-1090:fix pact provider issue

Jenkinsfile_CNP, Jenkinsfile_nightly, README.md, docker-compose.yml, src/functionalTest/resources/features/F-001/F-001-Base-Root.td.json, src/functionalTest/resources/features/F-001/S-020_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-001/S-020_Get_Role_Assignments_Search_Query.td.json, src/functionalTest/resources/features/F-001/S-020_Get_Role_Assignments_Search_Query_Second_ActorId.td.json, src/functionalTest/resources/features/F-002/F-002-Base-Root.td.json, src/functionalTest/resources/features/F-002/S-030_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-003/F-003-Base-Root.td.json, src/functionalTest/resources/features/F-005/F-005-Base-Root.td.json, src/functionalTest/resources/features/F-006/F-006-Base-Root.td.json, src/functionalTest/resources/features/F-006/F-006_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-006/S-083_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-006/S-087_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-007/F-007-Base-Root.td.json, src/functionalTest/resources/features/common/CreationDataBaseForRoleAssignment.td.json, src/functionalTest/resources/features/common/DeleteDataForRoleAssignments.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentEntitySpecifications.java, src/main/resources/application.yaml, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/UserTokenProviderConfig.java
=> Update the Service user and befta secrets

src/main/resources/application.yaml
whitelisting wa_task_management_api service
```
[ ] Yes
[x] No
```
=> whitelisting wa_task_management_api service

README.md, charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, docker-compose.yml
=> added wa-iac service in whitelist

README.md, charts/am-role-assignment-service/values.yaml, docker-compose.yml, src/main/resources/application.yaml
Added wa_task_configuration_api into aat service whitelist
```
[ ] Yes
[ ] No
```
=> added wa service

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/requirements.yaml
https://tools.hmcts.net/jira/browse/AM-1105
```
[ ] Yes
[X] No
```
=> Update java chart abd bump up chart version

src/main/java/uk/gov/hmcts/reform/roleassignment/data/HistoryRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/ActorCache.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/main/resources/db/changelog/db.changelog-AM-1108_6.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-1108
Performance testing support
```
[ ] Yes
[x ] No
```
=> Am 1108 performance testing support

src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-005/S-059.td.json, src/functionalTest/resources/features/F-005/S-059_CreationDataForRoleAssignment.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/RoleAssignmentResource.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java
Fixing the string based actor Id issue.
```
[ ] Yes
[x] No
```
=> retrieve data service and test cases fixed for string actorId

src/functionalTest/resources/features/F-001/S-004.td.json, src/functionalTest/resources/features/F-001/S-005.td.json, src/functionalTest/resources/features/F-001/S-014.td.json, src/functionalTest/resources/features/F-001/S-020.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentApplication.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/security/IdamRoleService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/AM-1120
Enable caching and response change in RAS
```
[ ] Yes
[x ] No
```
=> Am 1120 enable caching response change

src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-007/F-007_Test_Data_Base.td.json, src/functionalTest/resources/features/F-007/S-071.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java
As per the suggestions from Jon, we have added all the role configuration in the response of the 
get role API.
```
[ ] Yes
[x] No
```
=> Add pattern details to get role endpoint

broker-compose.yml, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentProviderTestConfiguration.java
https://tools.hmcts.net/jira/browse/AM-1115
updated provider pact
```
[ ] Yes
[x ] No
```
=> Am 981 updated provider pact

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
https://tools.hmcts.net/jira/browse/AM-1117
Improve line and mutation coverage.
Updated log success message. 
```
[ ] Yes
[x ] No
```
=> Am 1117 mutation test

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-1137
```
[ ] Yes
[X] No
```
=> Added method call to sync branches

src/main/java/uk/gov/hmcts/reform/roleassignment/config/CacheControlConfig.java
Updated etag scope in RAS
```
[ ] Yes
[ ] No
```
=>  updated etag scope in RAS

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java
https://tools.hmcts.net/jira/browse/AM-1128
=> AM-1128 - Pact Provider - Create Api - Additional Scenarios

build.gradle, src/main/resources/db/changelog/db.changelog-master.xml
=> new index on history table

src/contractTest/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentProviderTestConfiguration.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/resources/attributesSearchQuery.json
https://tools.hmcts.net/jira/browse/AM-1129
PACT Implementation for POST /am/role-assignments/query ProviderTest
[ ] Yes
[x] No
=> AM-1129: RAS Search Query Pact Provider Test

src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditInterceptor.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/JwtGrantedAuthoritiesConverter.java
AM-1126:Logs refactoring for perf test
```
[ ] Yes
[ ] No
```
=> AM-1126:Logs refactoring for perf test

src/main/resources/bootstrap.yml
Not available
```
[ ] Yes
[X] No
```
=> Remove s2s mount reference

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-1158
=> AM-1158 addressing CVEs

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-020_Get_Role_Assignments_Search_Query.td.json, src/functionalTest/resources/features/F-001/S-020_Get_Role_Assignments_Search_Query_Second_ActorId.td.json, src/functionalTest/resources/features/F-001/S-109.td.json, src/functionalTest/resources/features/F-001/S-109_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-005/S-051.td.json, src/functionalTest/resources/features/F-005/S-052.td.json, src/functionalTest/resources/features/F-005/S-054.td.json, src/functionalTest/resources/features/F-005/S-056.td.json, src/functionalTest/resources/features/F-005/S-057.td.json, src/functionalTest/resources/features/F-005/S-058_GetDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-005/S-059.td.json, src/functionalTest/resources/features/F-006/S-081.td.json, src/functionalTest/resources/features/F-006/S-082.td.json, src/functionalTest/resources/features/F-006/S-083.td.json, src/functionalTest/resources/features/F-006/S-084.td.json, src/functionalTest/resources/features/F-006/S-085.td.json, src/functionalTest/resources/features/F-006/S-086.td.json, src/functionalTest/resources/features/F-006/S-087.td.json, src/functionalTest/resources/features/common/RequestedRole.td.json, src/functionalTest/resources/features/common/ResponseRequestedRole.td.json, src/functionalTest/resources/features/common/ResponseRoleAssignment.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtilTest.java
Fix Authorisation Issue
Fix Authorisation Issue
```
[ ] Yes
[x ] No
```
=> authorisation issue fix.

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Request.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/CreatedTimeComparatorTest.java
=> updated the zoned datetime for create timestamp as well

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Request.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/CreatedTimeComparatorTest.java
Reverts hmcts/am-role-assignment-service#594
=> Revert "updated the zoned datetime for create timestamp as well"

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
=> Swagger documentation update

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Request.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/CreatedTimeComparatorTest.java
=> updated the zoned datetime for create timestamp

Jenkinsfile_nightly, build.gradle, charts/am-role-assignment-service/values.aat.template.yaml, charts/am-role-assignment-service/values.yaml, src/main/java/uk/gov/hmcts/reform/roleassignment/RoleAssignmentApplication.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/AM-1166
Replace TTL base simple cache with Caffeine  Cache  for Bearer Token
```
[ ] Yes
[x ] No
```
=> AM-1166  implemented the Caffeine Cache.

charts/am-role-assignment-service/values.aat.template.yaml
disable caching in aat.
disable caching in aat.
```
[ ] Yes
[x ] No
```
=> AM-1166  disable caching on aat.

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentServiceTest.java
https://tools.hmcts.net/jira/browse/AM-1171
RAS - Code coverage improvement to 95%
```
[ ] Yes
[ x] No
```
=> AM-1171  code coverage of createroles package.

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, docker-compose.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1188
whitelist the micro service - xui_webapp
```
[ ] Yes
[ x] No
```
=> AM-1188  whitelisting the xui_webapp service in RAS.

config/owasp/suppressions.xml
=> suppressing cve

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.preview.template.yaml, charts/am-role-assignment-service/values.yaml
Disable hystrix in AAT
Disable hystrix in AAT
```
[ ] Yes
[ x] No
```
=> disable hystrix  in AAT.

src/main/resources/application.yaml
Increase hysrtix timeout 
Increase hysrtix timeout 
```
[ ] Yes
[ x] No
```
=> increased hystrix time out to handle timeout exception.

charts/am-role-assignment-service/Chart.yaml, config/owasp/suppressions.xml
=> chart update as required by jenkins

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1203
update feign client timeout.
```
[ ] Yes
[x ] No
```
=> update feign client timeout

audit.json
https://tools.hmcts.net/jira/browse/AM-1196
=> AM-1196 fix failing build

charts/am-role-assignment-service/requirements.yaml
=> AM-1196 deleting unsupported file

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java
detached entity
detached
```
[ ] Yes
[ ] No
```
=> deteched_entity issue.

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java
https://tools.hmcts.net/jira/browse/AM-1216
Detached entity exception.
```
[ ] Yes
[ x] No
```
=> Deteched entity issue

src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditInterceptor.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentEntitySpecifications.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/data/ActorCacheEntityTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/model/AssignmentTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/feignclients/configuration/DatastoreFeignClientInterceptorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureToggleServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtilTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtilsTest.java
https://tools.hmcts.net/jira/browse/AM-1215
=> AM-1215 sonar bugs and smells fix

build.gradle
https://tools.hmcts.net/jira/browse/AM-1220
=> AM-1220 Tomcat Upgrade

build.gradle, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtilTest.java
Begin and Endtime issue
https://tools.hmcts.net/jira/browse/AM-1236
=> Am 1214 begin and endtime issue fix

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java
https://tools.hmcts.net/jira/browse/AM-1238
=> Am 1214 fix for requestedRoles coming back as empty

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.preview.template.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml
=> added the Hikari connection pool settings.

build.gradle
=> CVE Fix for commons-io

src/main/resources/application.yaml
Latest DB connection pool issue fix
```
[ ] Yes
[x] No
```
=> updated the max pool size settings for DB

src/main/resources/application.yaml
=> updated the keepAlive time in the connection pool settings

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-1321
=> AM-1321 adding contract test report to artifacts in Jenkins

.dependabot/config.yml, charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.preview.template.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yml
NA
Dependabot and secret fix
```
[ ] Yes
[x] No
```
=> Dependabot and secret fix

src/functionalTest/resources/features/F-009/F-009-Base-Root.td.json, src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-009/F-009_Test_Data_Base.td.json, src/functionalTest/resources/features/F-009/S-120.td.json, src/functionalTest/resources/features/F-009/S-121.td.json, src/functionalTest/resources/features/F-009/S-122.td.json, src/functionalTest/resources/features/F-009/S-122_GetDataForRoleAssignments.td.json, src/functionalTest/resources/features/common/RequestedRoleSalariedJudge.td.json, src/functionalTest/resources/features/common/ResponseRequestedRoleSalariedJudge.td.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryTest.java
https://tools.hmcts.net/jira/browse/AM-1315
AM-1315: JRD - Additional tests for salaried judges in RAS. Automation Tests.
[ ] Yes
[x] No
=> AM-1315: JRD - Additional tests for salaried judges in RAS

infrastructure/main.tf, src/main/resources/application.yaml
NA
Enable DB self service read only access
```
[ ] Yes
[X] No
```
=> Enable DB self service read only access

audit.json
NA
Updating the audit.json file.
```
[ ] Yes
[x] No
```
=> Updating the audit.json file.

build.gradle
=> Spring upgrade

src/main/java/uk/gov/hmcts/reform/roleassignment/config/SwaggerConfiguration.java
https://tools.hmcts.net/jira/browse/AM-1395
=> Swagger Request Url Fix

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/RetrieveDataService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/AM-1418
=> AM-1418 - Junit Coverage

src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-005/S-053.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PrepareResponseService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/v1/V1.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/SmokeTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java
https://tools.hmcts.net/jira/browse/AM-1393
AM-1393: Convert the 404 to 200 get GetAssignmentsByActorId.
```
[ ] Yes
[x] No
```
=> AM-1393: Convert the 404 to 200 get GetAssignmentsByActorId.

src/main/java/uk/gov/hmcts/reform/roleassignment/config/SecurityEndpointFilter.java
https://tools.hmcts.net/jira/browse/AM-1424
(fix): Removed the unnecessary logging.
```
[ ] Yes
[x] No
```
=> (fix): Removed the unnecessary logging.

src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditInterceptor.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditAspect.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/ExpressionEvaluator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/FeatureFlagController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/GenericArrayUserType.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/RoleConfig.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/FeatureFlagEnum.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/AuditLoggerUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/CorrelationInterceptorUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/FilterRequestUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/ValidationUtil.java, src/main/resources/validationrules/iac/iac-case-role-validation.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
https://tools.hmcts.net/jira/browse/AM-1411
All the below sonar severities brought down to zero in RAS.
- Blocker
- Critical
- Major
- Minor
- Info
```
[ ] Yes
[x] No
```
=> AM-1411: Fix sonar vulnerabilities in RAS

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/Assignment.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/PersistenceUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
Reverts hmcts/am-role-assignment-service#834
=> Revert "Am-1413_Pact_testing_issues_RAS"

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentIdentity.java
https://tools.hmcts.net/jira/browse/AM-1459
Fix the BEFTA breaking changes.
```
[ ] Yes
[x] No
```
=> (fix): Fixing the tests.

src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentEntitySpecifications.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/QueryRequest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentEntitySpecificationsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java
Jira link: https://tools.hmcts.net/jira/browse/AM-1433
=> Am-1433 mutation test advance query

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/QueryAssignmentIntegrationTest.java
https://tools.hmcts.net/jira/browse/AM-1434
1. Integration test for Advance query API
```
[ ] Yes
[ X] No
```
=> AM 1434 Integration test for advance querry API

.github/workflows/autoupdate.yml, Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java, src/functionalTest/resources/features/F-009/F-009-Base-Root.td.json, src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-009/F-009_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-009/F-009_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-009/F-009_DeleteRoleAssignmentsByActorId.td.json, src/functionalTest/resources/features/F-009/F-009_Test_Data_Base.td.json, src/functionalTest/resources/features/F-009/S-172.td.json, src/functionalTest/resources/features/F-009/S-173.td.json, src/functionalTest/resources/features/F-009/S-174.td.json, src/functionalTest/resources/features/F-009/S-175.td.json, src/functionalTest/resources/features/F-009/S-175_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-009/S-175_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-009/S-183.td.json, src/functionalTest/resources/features/F-009/S-183_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-009/S-183_DeleteDataForMultipleRoleAssignments.td.json, src/functionalTest/resources/features/F-009/S-184.td.json, src/functionalTest/resources/features/F-009/S-186.td.json, src/functionalTest/resources/features/F-009/S-187.td.json, src/functionalTest/resources/features/F-009/S-187_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-009/S-187_DeleteDataForMultipleRoleAssignments.td.json, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentIdentity.java
https://tools.hmcts.net/jira/browse/AM-1436
Created Advance query functional tests.
[ ] Yes
[x] No
=> AM-1436 Advance query functional tests

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetActorByIdRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PageHolder.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ThreadSafePage.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java
https://tools.hmcts.net/jira/browse/AM-1451
RAS code improvement
```
[ ] Yes
[x ] No
```
=> Am 1451 ras code improvement

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetActorByIdRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PageHolder.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ThreadSafePage.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java
https://tools.hmcts.net/jira/browse/AM-1435
=> 1435 pact provider update

security.sh
https://tools.hmcts.net/jira/browse/AM-1473
=> 1473 zap security fix

build.gradle
https://tools.hmcts.net/jira/browse/AM-1399
=> 1399 - fixing pact pipeline publishing

src/functionalTest/resources/features/F-009/F-009.feature
https://tools.hmcts.net/jira/browse/AM-1493
```
[ ] Yes
[x] No
```
=> Advance Query release issue fix

src/main/resources/application.yaml
AM-1495: Update the Hikari pool settings.
AM-1495: Update the Hikari pool settings.
```
[ ] Yes
[x] No
```
=> AM-1495: Update the Hikari pool settings.

src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java
updated the provider pact
```
[ ] Yes
[x] No
```
=> updated the provider pact

src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-009/S-175.td.json
https://tools.hmcts.net/jira/browse/AM-1493
Functional Test fix.
[ ] Yes
[x] No
=> AM1493: Functional Test fix.

src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java
Jira Link: https://tools.hmcts.net/jira/browse/AM-1510
=> AM-1510 PACT Provider Advance Delete

.github/workflows/autoupdate.yml, src/test/resources/db/performance/insert_bulk_assignments.sql
https://tools.hmcts.net/jira/browse/AM-1485
Create Bulk Assignments Script
```
[ ] Yes
[x ] No
```
=> Create Bulk Assignments Script

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java
NA
Minor code refactoring.
```
[ ] Yes
[x] No
```
=> Minor code refactoring.

src/functionalTest/resources/features/F-010/F-010-Base-Root-Create.td.json, src/functionalTest/resources/features/F-010/F-010-Base-Root.td.json, src/functionalTest/resources/features/F-010/F-010.feature, src/functionalTest/resources/features/F-010/F-010_Test_Data_Base-Create.td.json, src/functionalTest/resources/features/F-010/F-010_Test_Data_Base.td.json, src/functionalTest/resources/features/F-010/S-190.td.json, src/functionalTest/resources/features/F-010/S-190_DeleteDataForRoleAssignmentsForOrgRoles.td.json, src/functionalTest/resources/features/F-010/S-190_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-191.td.json, src/functionalTest/resources/features/F-010/S-191_DeleteDataForRoleAssignmentsForOrgRoles.td.json, src/functionalTest/resources/features/F-010/S-191_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-192.td.json, src/functionalTest/resources/features/F-010/S-192_DeleteDataForRoleAssignmentsForOrgRoles.td.json, src/functionalTest/resources/features/F-010/S-192_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-193.td.json, src/functionalTest/resources/features/F-010/S-193_DeleteDataForRoleAssignmentsForOrgRoles.td.json, src/functionalTest/resources/features/F-010/S-193_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-194.td.json
https://tools.hmcts.net/jira/browse/AM-1508
Delete Advance Query functional test automation.
[ ] Yes
[x] No
=> AM-1508: functional test automation

build.gradle
AM-1503
Fix CVE issues.CVE-2021-35515, CVE-2021-35516, CVE-2021-35517, CVE-2021-36090
```
[ ] Yes
[x] No
```
=> Fix CVE issues.CVE-2021-35515, CVE-2021-35516, CVE-2021-35517, CVE-2021-36090

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/deleteroles/DeleteRoleAssignmentOrchestratorTest.java
Jira Link: https://tools.hmcts.net/jira/browse/AM-1506
=> AM-1506: Mutation testing for advance delete api

charts/am-role-assignment-service/Chart.yaml, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentOrchestrator.java
https://tools.hmcts.net/jira/browse/AM-1540
Update chart version.
```
[ ] Yes
[x] No
```
=> Update chart version.

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentCreateAndDeleteIntegrationTest.java, src/integrationTest/resources/sql/insert_multiple_assignments_to_delete.sql
https://tools.hmcts.net/jira/browse/AM-1507
=> 1507 adv delete integration tests

build.gradle
AM-1550
CVE fix CVE-2021-28170
```
[ ] Yes
[x] No
```
=> Fixing the CVE-2021-28170

build.gradle
Am-1550
Fixing the CVE-2021-28170,CVE-2021-22119
```
[ ] Yes
[x] No
```
=> Fixing the CVE-2021-28170,CVE-2021-22119

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-1579
=> 1579 CVE nimbus lang tang

src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java
https://tools.hmcts.net/jira/browse/AM-1576
=> disabling static roles pact

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CCDCaseRolesTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
https://tools.hmcts.net/jira/browse/AM-1619
Junit for ccd roles
```
[ ] Yes
[X ] No
```
=> junit for ccd roles

src/main/resources/application.yaml
Fortify Fix.
```
[ ] Yes
[x] No
```
=> Fixing the code.

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java
https://tools.hmcts.net/jira/browse/AM-1736
=> Case allocator Junit

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-123.td.json, src/functionalTest/resources/features/F-001/S-123_CreateDataForRoleAssignment.td.json
https://tools.hmcts.net/jira/browse/AM-1725
```
[ ] Yes
[ X] No
```
=> FTA for dummy jurisdiction

infrastructure/main.tf
=> TF update for DB

build.gradle
CVE-2021-22096 fix
```
[ ] Yes
[x] No
```
=> CVE-2021-22096 fix

infrastructure/main.tf
=> Update DB secrets for lower envs - PerfTest

infrastructure/main.tf
Updating the pwd for V11
```
[ ] Yes
[x] No
```
=> Updating the pwd for V11

infrastructure/main.tf
Create the V11 DB password using terraform.
```
[ ] Yes
[x] No
```
=> Create the V11 DB password using terraform.

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.aat.template.yaml, charts/am-role-assignment-service/values.yaml, infrastructure/main.tf
Pointing to V11 DB post migration
```
[ ] Yes
[x] No
```
=> Pointing to V11 DB post migration

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-1774
Added new ccd roles as per definition store production
```
[ ] Yes
[x] No
```
=> new CCD case roles

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-1788
v11 DB migration completed. Remove v9.6 DB.
```
[ ] Yes
[X ] No
```
=> Remove v9.6 DB

src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-1789
added extra condition for fixing ccd duplicate case identification
```
[ ] Yes
[x] No
```
=> added extra condition for fixing ccd duplicate case identification

src/functionalTest/resources/features/F-001/S-202_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-203_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-204_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-205_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-206.td.json, src/functionalTest/resources/features/F-001/S-206_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-103.td.json, src/functionalTest/resources/features/F-008/S-104.td.json, src/functionalTest/resources/features/F-008/S-104_Multiple_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-106.td.json, src/functionalTest/resources/features/F-008/S-106_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-107.td.json, src/functionalTest/resources/features/F-008/S-107_Multiple_Case_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-201_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-207.td.json, src/functionalTest/resources/features/F-008/S-207_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-208_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-008/S-209_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-009/S-172.td.json, src/functionalTest/resources/features/F-009/S-173.td.json, src/functionalTest/resources/features/F-009/S-174.td.json, src/functionalTest/resources/features/F-010/S-190_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-191_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-192_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-193_Multiple_Org_Role_Creation.td.json, src/main/resources/roleconfig/role_iac.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryCaseRoleTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-1799
updating the substantive flag for TCW and case-allocator case role
```
[ ] Yes
[x] No
```
=> updating the substantive flag for TCW and case-allocator case role

src/functionalTest/resources/features/F-001/S-202_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-203_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-204_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-205_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-206.td.json, src/functionalTest/resources/features/F-001/S-206_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-103.td.json, src/functionalTest/resources/features/F-008/S-104.td.json, src/functionalTest/resources/features/F-008/S-104_Multiple_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-106.td.json, src/functionalTest/resources/features/F-008/S-106_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-107.td.json, src/functionalTest/resources/features/F-008/S-107_Multiple_Case_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-201_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-207.td.json, src/functionalTest/resources/features/F-008/S-207_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-208_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-008/S-209_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-009/S-172.td.json, src/functionalTest/resources/features/F-009/S-173.td.json, src/functionalTest/resources/features/F-009/S-174.td.json, src/functionalTest/resources/features/F-010/S-190_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-191_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-192_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-193_Multiple_Org_Role_Creation.td.json, src/main/resources/roleconfig/role_iac.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryCaseRoleTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryOrgRoleTest.java
Reverts hmcts/am-role-assignment-service#1055
=> Revert "updating the substantive flag for TCW and case-allocator case role"

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-1829
additional roles added for divorce jurisdiction
```
[ ] Yes
[x] No
```
=> additional roles added for divorce jurisdiction

src/functionalTest/resources/features/F-001/S-202_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-203_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-204_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-205_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-001/S-206.td.json, src/functionalTest/resources/features/F-001/S-206_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-103.td.json, src/functionalTest/resources/features/F-008/S-104.td.json, src/functionalTest/resources/features/F-008/S-104_Multiple_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-106.td.json, src/functionalTest/resources/features/F-008/S-106_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-107.td.json, src/functionalTest/resources/features/F-008/S-107_Multiple_Case_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-201_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-207.td.json, src/functionalTest/resources/features/F-008/S-207_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-008/S-208_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-008/S-209_Org_Role_Creation_For_Requester.td.json, src/functionalTest/resources/features/F-009/S-172.td.json, src/functionalTest/resources/features/F-009/S-173.td.json, src/functionalTest/resources/features/F-009/S-174.td.json, src/functionalTest/resources/features/F-010/S-190_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-191_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-192_Multiple_Org_Role_Creation.td.json, src/functionalTest/resources/features/F-010/S-193_Multiple_Org_Role_Creation.td.json, src/main/resources/roleconfig/role_iac.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryCaseRoleTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryOrgRoleTest.java
restore substantive code.
```
[ ] Yes
[x] No
```
=> restore substantive code.

src/main/resources/application.yaml
=> disabling the debug log specially for FTA

Jenkinsfile_nightly
=> disabling the fortify step from nightly build

src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java
Reverts hmcts/am-role-assignment-service#1077
=> Revert "Am 1837"

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/QueryAssignmentIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditEntry.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditLogFormatter.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/LogAudit.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditAspect.java, src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditContext.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/AuditLoggerUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditLogFormatterTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/auditlog/aop/AuditAspectTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/AuditLoggerUtilTest.java
https://tools.hmcts.net/jira/browse/AM-1881
Audit an loggings
```
[ ] Yes
[ X] No
```
=> Audit and logging modifications

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
=> Added a generic exception in persistActorCache for DB querying

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/FilterRequestUtil.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/util/FilterRequestUtilTest.java
https://tools.hmcts.net/jira/browse/AM-1939
=> Modified wrapped errors into 422 errors.

src/main/resources/application.yaml
increased the max db connection pool size
```
[ ] Yes
[x] No
```
=> increased the max pool size

src/main/resources/META-INF/kmodule.xml
=> disabling the dev super user role

src/main/java/uk/gov/hmcts/reform/roleassignment/config/RasPostgreSQL9Dialect.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentEntitySpecifications.java, src/main/resources/application.yaml, src/main/resources/db/migration/V1_6__adding_new_indexes.sql
https://tools.hmcts.net/jira/browse/AM-1967
Indexes for jsonb values
```
[ ] Yes
[X ] No
```
=> New json contains fxn

charts/am-role-assignment-service/Chart.yaml
[AM-1997](https://tools.hmcts.net/jira/browse/AM-1997)
```
[ ] Yes
[x] No
```
=> bumping the chart version

build.gradle, config/owasp/suppressions.xml, src/main/resources/application.yaml
=> remove max life on connection pool

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml
=> Increase the application delay

src/main/resources/db/migration/V1_7__adding_new_history_indexe.sql
=> Updated the history table index

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/QueryAssignmentIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentCreateAndDeleteIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/config/SecurityEndpointFilter.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/exception/UnauthorizedException.java, src/main/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtils.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/oidc/IdamRepositoryTest.java
exception handling on idam service call
```
[ ] Yes
[ X] No
```
=> Exception handling for idam service call

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/advice/exception/UnauthorizedException.java, src/main/java/uk/gov/hmcts/reform/roleassignment/util/SecurityUtils.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/getroles/RetrieveRoleAssignmentOrchestratorTest.java
test coverage
```
[ ] Yes
[ X] No
```
=> coverage tests

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-1979
New ccd case roles for Adoption
```
[ ] Yes
[x] No
```
=> New ccd case roles for adoption

lib/AI-Agent.xml, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/RetrieveDataService.java
=> Added methods execution time to be monitored

src/main/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditInterceptor.java, src/test/java/uk/gov/hmcts/reform/roleassignment/auditlog/AuditInterceptorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/launchdarkly/FeatureConditionEvaluationTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
=> Added a mock for the logger test case

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-2030
updated the existing role with private law
```
[ ] Yes
[x] No
```
=> new role for support for private law

charts/am-role-assignment-service/Chart.yaml
=> Updated the chart version

Jenkinsfile_nightly, build.gradle
=> Ignore fortify

charts/am-role-assignment-service/Chart.yaml
https://tools.hmcts.net/jira/browse/AM-2066
```
[ ] Yes
[x] No
```
=> upgraded the java chart version

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2009
CVE fix for drool
```
[ ] Yes
[x] No
```
=> removed cve suppression

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java, src/smokeTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java
https://tools.hmcts.net/jira/browse/AM-2068
Gradle upgrade to 7.4.1
```
[ ] Yes
[ X] No
```
=> upgrade to gradle 7.4.1

src/main/resources/db/migration/V1_10__iac_substantive_flag_config_tables.sql
substative flag script
```
[ ] Yes
[ X] No
```
=> substantive flg script

build.gradle
es this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> Reverted pitest change

build.gradle
=> Updated poi, poi-ooxml & poi-scratchpad to 5.2.1

build.gradle
=> Cve fix, jackson core version update 2.13.2

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolJudicialCategoryCaseRoleTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SscsCaseRolesDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryCaseTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-2078
=> Unit testing for SSCS roles

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2093
```
[ ] Yes
[x] No
```
=> updated the iac service position in the list

build.gradle
https://tools.hmcts.net/jira/browse/AM-2098
postgres version upgrade
```
[ ] Yes
[x] No
```
=> postgres version upgrade

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2059
=> 2059 SSCS Hearing Roles Drools Unit Tests

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/RoleCategory.java, src/main/resources/META-INF/kmodule.xml, src/main/resources/roleconfig/role_common.json, src/main/resources/roleconfig/role_iac.json, src/main/resources/roleconfig/role_sscs.json, src/main/resources/validationrules/sscs/common/sscs-case-role-validation.drl, src/main/resources/validationrules/sscs/sscs-case-role-validation-judicial.drl, src/main/resources/validationrules/sscs/sscs-case-role-validation-legal-ops.drl, src/main/resources/validationrules/wa/wa-test-jurisdiction-bypass.drl
https://tools.hmcts.net/jira/browse/AM-1925
Staff roles for sscs
```
[ ] Yes
[x] No
```
=> Am 2095 sscs staff roles

build.gradle, src/main/resources/validationrules/core/load-case-data.drl
added wa services to avoid ccd case load
```
[ ] Yes
[x] No
```
=> added wa services to avoid ccd case load

src/main/resources/validationrules/core/load-case-data.drl
Reverts hmcts/am-role-assignment-service#1238
=> Revert "added wa services to avoid ccd case load"

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SscsCaseRolesDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/StaffCategoryOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2101
=> Unit testing for latest Staff Org Roles and Case Role

src/main/resources/validationrules/iac/iac-case-role-validation-admin.drl, src/main/resources/validationrules/iac/iac-case-role-validation-judicial.drl, src/main/resources/validationrules/iac/iac-case-role-validation-legal-ops.drl
Challenged role endtime convert to UTC
```
[ ] Yes
[X ] No
```
=> challenged access role endtime corrections

src/main/resources/application.yaml
service list fixing
```
[ ] Yes
[ X] No
```
=> whitelisting service missing terminal

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2139
Whitelist HMC service
```
[ ] Yes
[x] No
```
=> whitelisted hmc service

build.gradle
https://tools.hmcts.net/jira/browse/AM-2156
=> 2156 - fix nightly build

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2166
whitelisting ccd_case_disposer app
```
[ ] Yes
[x] No
```
=> whitelisting ccd_case_disposer app

src/main/resources/roleconfig/role_civil.json, src/main/resources/roleconfig/role_common.json, src/main/resources/roleconfig/role_iac.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2185
New roles added for Civil staff Org roles
```
[ ] Yes
[x] No
```
=> AM_2185 : New roles added for Civil staff Org roles

src/main/java/uk/gov/hmcts/reform/roleassignment/util/JacksonUtils.java, src/main/resources/validationrules/ccd/ccd-case-role-validation.drl, src/main/resources/validationrules/core/load-case-data.drl
https://tools.hmcts.net/jira/browse/AM-2193
added ccd case disposer for deletion of case roles
```
[ ] Yes
[x] No
```
=> added ccd case disposer for deletion of case roles

src/main/resources/validationrules/core/load-case-data.drl
ccd case role fix
```
[ ] Yes
[X ] No
```
=> ccd_data role issue fix

src/main/resources/roleconfig/role_common.json
=> updated the civil role names

src/main/resources/roleconfig/role_common.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2205
updated the global roles for flexibility
```
[ ] Yes
[x] No
```
=> updated the global roles for flexibility

src/main/resources/validationrules/core/specific-access-global.drl
https://tools.hmcts.net/jira/browse/AM-2211
removed the process and reference check for delete requests
```
[ ] Yes
[x] No
```
=> removed the process and reference check for delete requests

build.gradle
revert the ben manes version
```
[ ] Yes
[x] No
```
=> revert the ben manes version

charts/am-role-assignment-service/Chart.yaml
=> Upgrade base java chart

charts/am-role-assignment-service/Chart.yaml, config/owasp/suppressions.xml
=> Suppression added

config/owasp/suppressions.xml
=> Suppression for log4j

src/main/resources/db/migration/V2_4__ccd_1_0_flag_add.sql
adding ccd flag
```
[ ] Yes
[ X] No
```
=> ccd flag add

build.gradle
https://tools.hmcts.net/jira/browse/AM-2291
```
[X] Yes
[ ] No
```
=> RAS:Merge renovate bot pr's

src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/createroles/CreateRoleAssignmentService.java
https://tools.hmcts.net/jira/browse/AM-2305
```
[ ] Yes
[X] No
```
=> removing code smells

docker/database/Dockerfile, infrastructure/terraform.tf
Merging the renovate PR on 16Aug 2022
```
[ ] Yes
[X] No
```
=> Merge Renovate PR

src/main/resources/META-INF/kmodule.xml, src/main/resources/roleconfig/role_common.json, src/main/resources/validationrules/core/specific-access-global.drl, src/main/resources/validationrules/privatelaw/privatelaw-case-role-validation-judicial.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java
https://tools.hmcts.net/jira/browse/AM-2320
specific and challenged access for privatelaw and judicial case roles
```
[ ] Yes
[ X] No
```
=> specific and challenged access changes

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ConflictOfInterestTest.java
https://tools.hmcts.net/jira/browse/AM-2363
```
[ ] Yes
[ x] No
```
=> Am 2363 conflictroles

build.gradle
https://tools.hmcts.net/jira/browse/AM-2404
```
[ ] Yes
[X] No
```
=> CVE issues and build failures

build.gradle, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java
https://tools.hmcts.net/jira/browse/AM-2402
```
[ ] Yes
[X] No
```
=> CIVIL_WA JUNIT for specific case region id check

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-2387
New CCD role configuration
```
[ ] Yes
[ X] No
```
=> CCD new case role configuration

build.gradle
https://tools.hmcts.net/jira/browse/AM-2443
jit pack removal to fix build
```
[ ] Yes
[X ] No
```
=> build fix to remove jitpack

build.gradle
=> Fix build failure

src/main/resources/validationrules/iac/common/iac-case-role-validation.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/IacStaffCaseRoleTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-2438
=> ia_delete_creator_case_roles drool rule

src/main/java/uk/gov/hmcts/reform/roleassignment/config/AuthCheckerConfiguration.java
fortify scan fix
```
[ ] Yes
[ X] No
```
=> fortify scan fix

build.gradle
https://tools.hmcts.net/jira/browse/AM-2538
```
[ ] Yes
[X] No
```
=> Nightly Build failure -30/11/2022

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2636
```
[ ] Yes
[X] No
```
=> Dependency Check

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-2637
ccd case roles for Barrister and Intervener
```
[ ] Yes
[X ] No
```
=> ccd case roles for Barrister and Intervener

infrastructure/variables.tf
remove depricated vars
```
[ ] Yes
[ X] No
```
=> removing depricate infra vars

build.gradle
https://tools.hmcts.net/jira/browse/AM-2664
```
[ ] Yes
[X] No
```
=> Swagger not working

build.gradle, src/functionalTest/resources/features/F-015/S-223.td.json, src/main/resources/roleconfig/role_common.json
=> remove duplicate role

src/main/resources/roleconfig/role_employment.json, src/main/resources/validationrules/employment/employment-case-role-validation-judicial.drl, src/main/resources/validationrules/employment/employment-case-role-validation-legal-ops.drl
https://tools.hmcts.net/jira/browse/AM-2614
package in drools rules fixed, duplicate role removed from json
```
[ ] Yes
[x] No
```
=> Am 2614 case roles fix

build.gradle, src/main/resources/roleconfig/role_employment.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java
* [AM-2831](https://tools.hmcts.net/jira/browse/AM-2831) _"ET_WA - Final round of review and testing of combined feature branches for release Employment_WA_1.0"_
* [AM-2614](https://tools.hmcts.net/jira/browse/AM-2614) _"ET_WA - Add CASE role validation drool rules in RAS application for STAFF And JUDICIARY"_
Additional code review changes for https://github.com/hmcts/am-role-assignment-service/pull/1863:
* update ET case role validation config.
* increase unit test scenarios for ET case role validation.
```
[ ] Yes
[x] No
```
=> AM-2831 additional code review changes for #1863

build.gradle, config/owasp/suppressions.xml, src/main/resources/roleconfig/role_common.json, src/main/resources/roleconfig/role_employment.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/DroolBase.java
* [AM-2831](https://tools.hmcts.net/jira/browse/AM-2831) _"ET_WA - Final round of review and testing of combined feature branches for release Employment_WA_1.0"_
* [AM-2688](https://tools.hmcts.net/jira/browse/AM-2688) _"ET_WA - Add mapping rules in ORM for STAFF users"_
* [AM-2611](https://tools.hmcts.net/jira/browse/AM-2611) _"ET_WA - Enable Specific and Challenged access for ET for both STAFF and JUDICIARY"_
* [AM-2614](https://tools.hmcts.net/jira/browse/AM-2614) _"ET_WA - Add CASE role validation drool rules in RAS application for STAFF And JUDICIARY"_
Code Review Changes For #1863
```
[ ] Yes
[*] No
```
=> AM-2831 Code Review Changes For #1863

Jenkinsfile_CNP, src/functionalTest/resources/features/F-015/S-223_Org_Role_Creation.td.json
https://tools.hmcts.net/jira/browse/AM-2846
```
[ ] Yes
[ *] No
```
=> AM-2846: For preview pipelines enable cleanup of helm releases

src/main/resources/validationrules/core/organisational-role-mapping-common.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2841
Add jurisdiction filter to system user hearings role (sscs & private law)
=> AM-2841: Add jurisdiction filter to system user hearings role (sscs & private law)

build.gradle, charts/am-role-assignment-service/values.preview.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2823
```
[ ] Yes
[ *] No
```
=> AM-2823-CVE-2023-20883 FIX

src/main/resources/roleconfig/role_common.json, src/main/resources/roleconfig/role_sscs.json
https://tools.hmcts.net/jira/browse/AM-2762
SSCS_WA - Add service in RAS json files for STAFF users
```
[ ] Yes
[x] No
```
=> AM-2762:SSCS_WA - enable SSCS service

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/AM-2738
Nightly build slack messaging removed
```
[ ] Yes
[x] No
```
=> AM-2738 Nightly build slack messaging removed

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/CreateRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/DeleteRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetActorByIdRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/GetRoleAssignmentProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/roleassignment/SearchQueryRoleAssignmentProviderTest.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/CreateAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/DeleteAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/GetAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/endpoints/QueryAssignmentController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PageHolder.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestrator.java
https://tools.hmcts.net/jira/browse/AM-2876
Checkstyle Code Formatting for uk.gov.hmcts.java 0.12.43
```
[ ] Yes
[x] No
```
=> AM-2876 Checkstyle Code Formatting for uk.gov.hmcts.java 0.12.43

src/main/resources/roleconfig/role_common.json, src/main/resources/validationrules/publiclaw/publiclaw-case-role-validation-legal-ops.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java
https://tools.hmcts.net/jira/browse/COT-433
FPL have requested a new case role **hearing-legal-adviser** for users that have the **tribunal-caseworker** role.
```
[ ] Yes
[x] No
```
=> COT-433:WA FPL new hearing-legal-advisor case role

audit.json
https://tools.hmcts.net/jira/browse/AM-2909
AM-2909 Zap Security Scan Failing for V2 URL
```
[ ] Yes
[x] No
```
=> 10112 Session Management Response Identified ignored added

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2930
CVE-2022-1415 Suppression
```
[ ] Yes
[x] No
```
=> AM-2930 CVE-2022-1415 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2930
CVE-2022-1415 drools upgraded 7.73.0.Final
```
[ ] Yes
[x] No
```
=> AM-2930 CVE-2022-1415 drools upgraded 7.73.0.Final

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2934
CVE-2023-42503 Suppression
```
[ ] Yes
[x] No
```
=> AM-2934 CVE-2023-42503 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2934
CVE-2023-42503 commons-compress upgraded 1.24.0
```
[ ] Yes
[x] No
```
=> AM-2934 CVE-2023-42503 commons-compress upgraded 1.24.0

src/main/resources/roleconfig/role_ccd.json
https://tools.hmcts.net/jira/browse/AM-2935
=> Allow more NFD case types

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/AM-2948
Temp disabling of Security Scan (Zap) in Nightly
```
[ ] Yes
[x] No
```
=> AM-2948 Temp disabling of Security Scan (Zap) in Nightly

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/main/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/data/RoleAssignmentRepository.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountControllerTest.java
https://tools.hmcts.net/jira/browse/AM-2907
Automate judicial user count per and post refresh of users
```
[ ] Yes
[x] No
```
=> AM-2907 Automate judicial user count per and post refresh of users

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2953
https://tools.hmcts.net/jira/browse/AM-2952
CVE-2022-4244 AM-2952 CVE-2022-4245 Shared Suppression
```
[ ] Yes
[x] No
```
=> AM-2953 CVE-2022-4244 AM-2952 CVE-2022-4245 Shared Suppression

src/main/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountController.java, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/UserCountService.java, src/test/java/uk/gov/hmcts/reform/roleassignment/controller/UserCountControllerTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/UserCountServiceTest.java
https://tools.hmcts.net/jira/browse/AM-2907
Refactor
```
[ ] Yes
[x] No
```
=> Am 2907 automate user count custom event reorg

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2960
provision terraform v15 server RAS Demo
```
[ ] Yes
[x] No
```
=> AM-2960 provision terraform v15 server RAS Demo

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2987 CVE-2023-42794
https://tools.hmcts.net/jira/browse/AM-2988 CVE-2023-42795
https://tools.hmcts.net/jira/browse/AM-2989 CVE-2023-45648
Tomcat version var created and upgraded to 9.0.82
```
[ ] Yes
[x] No
```
=> AM-2987 Tomcat version var created and upgraded to 9.0.82

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2975
Provision terraform v15 server RAS ITHC
```
[ ] Yes
[x] No
```
=> AM-2975 Provision terraform v15 server RAS ITHC

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml, src/main/resources/application.yaml, src/main/resources/roleconfig/role_common.json, src/main/resources/validationrules/core/organisational-role-mapping-common.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2954
```
[ ] Yes
[ *] No
```
=> AM-2954:  Create a new system role for Civil

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2975
provision terraform postgres v15 ITHC for second time as previous pr was overwritten from master branch sync
```
[ ] Yes
[x] No
```
=> Am 2975 provision terraform postgres v15 ITHC

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3002
CVE-2023-5072 Suppression
```
[ ] Yes
[x] No
```
=> AM-3002 CVE-2023-5072 Suppression

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2995
Provision terraform v15 server RAS Perftest
```
[ ] Yes
[x] No
```
=> AM-2995 Provision terraform v15 server RAS Perftest

charts/am-role-assignment-service/Chart.yaml, src/main/resources/roleconfig/role_common.json, src/main/resources/validationrules/core/organisational-role-mapping-common.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-3005
```
[ ] Yes
[ *] No
```
=> AM-3005: Add a new drool rule to support system user for IAC

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2960
Provision Pg v15 Demo User Host Secrets 
```
[ ] Yes
[x] No
```
=> Am 2960 Provision Pg v15 Demo User Host Secrets 

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2995
provision terraform postgres v15 perftest user host secrets
```
[ ] Yes
[x] No
```
=> Am 2995 provision terraform postgres v15 perftest

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2993
v15 Migration - put perftest log level to DEBUG
```
[ ] Yes
[x] No
```
=> AM-2993 v15 Migration - put perftest log level to DEBUG

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2993
v15 Migration - put ITHC log level to DEBUG
```
[ ] Yes
[x] No
```
=> AM-2993 v15 Migration - put ITHC log level to DEBUG

src/main/resources/application.yaml
Reverts hmcts/am-role-assignment-service#2042
=> Revert "AM-2993 v15 Migration - put perftest log level to DEBUG"

src/main/resources/application.yaml
Reverts hmcts/am-role-assignment-service#2044
=> Revert "AM-2993 v15 Migration - put ITHC log level to DEBUG"

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-3020
Resync ITHC and Perftest 
```
[x] Yes
[x] No
```
=> Am 3020 Resync ITHC and Perftest 

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2839
CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression
```
[ ] Yes
[x] No
```
=> AM-2839 CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3060
v15 Reader User Trigger ITHC, Perftest, Demo
```
[ ] Yes
[x] No
```
=> AM-3060 v15 Reader User Trigger

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2840
CVE-2022-45688 Remove Suppression
```
[ ] Yes
[x] No
```
=> AM-2840 CVE-2022-45688 Remove Suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3085
AM-3085 CVE-2023-33202 bouncycastle Suppression
```
[ ] Yes
[x] No
```
=> AM-3085 CVE-2023-33202 bouncycastle Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3090
CVE-2023-6378 Fix 
```
[ ] Yes
[x] No
```
=> Am 3090 CVE 2023 6378 fix

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3002
CVE-2023-5072 Fix json upgrade 20231013
```
[ ] Yes
[x] No
```
=> AM-3002 CVE-2023-5072 Fix json upgrade 20231013

src/main/resources/db/migration/V20240116_85__DTSAM-85_Enable_DISPOSER_1_0_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-85
```
[ ] Yes
[* ] No
```
=> DTSAM-85 : Enable 'disposer_1_0' RAS flag in PROD

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSAM-94
Review Health Checks with New Guidance - Enable Readiness and Liveness
```
[ ] Yes
[x] No
```
=> DTSAM-94 Review Health Checks with New Guidance 

charts/am-role-assignment-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSAM-104
Chart-java Upgrade 5.0.4
```
[ ] Yes
[x] No
```
=> DTSAM-104 Chart-java Upgrade 5.0.4

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSAM-134
Allow Flyway DB Migrations Out of Order
```
[ ] Yes
[x] No
```
=> DTSAM-134 Allow Flyway DB Migrations Out of Order

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-137
CVE-2023-34042 Suppression
```
[ ] Yes
[x] No
```
=> DTSAM-137 CVE-2023-34042 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-137
CVE-2023-34042 spring-security upgraded to 5.7.11
```
[ ] Yes
[x] No
```
=> DTSAM-137 CVE-2023-34042 spring-security upgraded to 5.7.11

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-154
https://tools.hmcts.net/jira/browse/DTSAM-155
CVE-2024-25710 CVE-2024-26308 Suppression
```
[ ] Yes
[x] No
```
=> DTSAM-154 DTSAM-155 CVE-2024-25710 CVE-2024-26308 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-154
https://tools.hmcts.net/jira/browse/DTSAM-155
CVE-2024-25710 CVE-2024-26308 Fix commons-compress upgraded to 1.26.0
```
[ ] Yes
[x] No
```
=> DTSAM-154 DTSAM-155 CVE-2024-25710 CVE-2024-26308 Fix 

src/functionalTest/resources/features/F-011/S-231.td.json, src/functionalTest/resources/features/F-011/S-231_Access_Requested.td.json, src/functionalTest/resources/features/F-011/S-232.td.json, src/functionalTest/resources/features/F-011/S-232_Access_Requested.td.json, src/functionalTest/resources/features/F-017/F-017-Base-Root.td.json, src/functionalTest/resources/features/F-017/S-256_DeleteDataForRoleAssignmentsForOrgRoles.td.json, src/functionalTest/resources/features/F-017/S-256_Org_Role_Creation.td.json
https://tools.hmcts.net/jira/browse/AM-3138
Updated end date to dynamic date for Specific Access Tests.
**Does this PR introduce a breaking change?** 
No
=> AM-3138: FTA fix.

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-3024
Schema Owner Fix
```
[ ] Yes
[x] No
```
=> AM-3024 Migrate Data RAS AAT - Schema Owner Fix

src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-009/S-175.td.json, src/functionalTest/resources/features/F-017/F-017.feature, src/functionalTest/resources/features/F-017/S-256.td.json, src/functionalTest/resources/features/F-017/S-256_Org_Role_Creation.td.json
https://tools.hmcts.net/jira/browse/AM-3138
Updated query and changed the actor id.
**Does this PR introduce a breaking change?** No
=> AM-3138: FTA fix

charts/am-role-assignment-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSAM-163
Reverting Preview CCD Data Store url
```
[ ] Yes
[x] No
```
=> DTSAM-163 Reverting Preview CCD Data Store url

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3024
Migrate Data RAS AAT - Schema Owner Bump 2
```
[ ] Yes
[x] No
```
=> AM-3024 Migrate Data RAS AAT - Schema Owner Bump 2

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3060
v15 Reader User Trigger 3 AAT, ITHC, Perftest, Demo
```
[ ] Yes
[x] No
```
=> AM-3060 v15 Reader User Trigger 3 AAT, ITHC, Perftest, Demo

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-185
CVE SUPPRESSION
```
[ ] Yes
[ *] No
```
=> DTSAM-185 : CVE Suppression CVE-2024-1597

charts/am-role-assignment-service/values.aat.template.yaml, src/main/java/uk/gov/hmcts/reform/roleassignment/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240328_236__DTSAM-236_sscs_challenged_flag_config_tables.sql, src/main/resources/validationrules/core/challenged-access-global.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/ChallengedAccessDroolsTest.java
https://tools.hmcts.net/jira/browse/DTSAM-236
```
[ ] Yes
[* ] No
```
=> DTSAM-236 :Challenged Access for Fee-Paid Judicial members

Jenkinsfile_nightly
Reverts hmcts/am-role-assignment-service#2202
=> Revert "DTSPO-17373 Jenkins Build Failed at Security Scan stage, Zap image up…"

src/main/resources/db/migration/V20240417_3076__AM-3076_Enable_sscs_wa_1_0_Prod.sql
https://tools.hmcts.net/jira/browse/AM-3076
Enable 'sscs_wa_1_0' in Prod
```
[ ] Yes
[x] No
```
=> AM-3076 Enable 'sscs_wa_1_0' in Prod

charts/am-role-assignment-service/Chart.yaml, charts/am-role-assignment-service/values.yaml
https://tools.hmcts.net/jira/browse/DTSAM-252
Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled
```
[ ] Yes
[x] No
```
=> DTSAM-252 Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled

Jenkinsfile_CNP, Jenkinsfile_nightly
[DTSAM-288](https://tools.hmcts.net/jira/browse/DTSAM-288) _"Temporary disable FTAs that use CCD Validation and fix issues"_
Temporary disable FTAs that use CCD Validation whilst we fix cases.
```
[ ] Yes
[x] No
```
=> DTSAM-288 Temp disable of FTAs with CCD Validation

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3060
Reader User Trigger 5 Prod
```
[ ] Yes
[x] No
```
=> AM-3060 Reader User Trigger 5 Prod

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSAM-303
Unsync Perftest from Master
```
[ ] Yes
[x] No
```
=> DTSAM-303 Unsync Perftest from Master

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSAM-303
Resize PG Perftest (part 1: apply default sku)
```
[ ] Yes
[x] No
```
=> DTSAM-303 Resize PG Perftest (part 1: apply default sku)

infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/browse/DTSAM-303
Perftest pgsql_sku = "GP_Standard_D8s_v3"
```
[ ] Yes
[x] No
```
=> Dtsam 303 resize pg perftest 2

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-3045
Decommission V11 DB - Resync ITHC with Master branch
```
[ ] Yes
[x] No
```
=> AM-3045 Decommission V11 DB - Resync ITHC with Master branch

src/main/resources/db/migration/V20240611_331__DTSAM-331_Enable_SSCS_CASE_ALLOCATOR_1_0_Prod.sql
[DTSAM-331](https://tools.hmcts.net/jira/browse/DTSAM-331) _"Enable 'sscs_case_allocator_1_0' RAS flag in PROD"_
Enable `sscs_case_allocator_1_0` RAS flag in PROD
```
[ ] Yes
[x] No
```
=> DTSAM-331 Enable sscs_case_allocator_1_0 RAS flag in PROD

Jenkinsfile_CNP, Jenkinsfile_nightly
Reverts hmcts/am-role-assignment-service#2277
=> Revert "DTSAM-385 Temp Disable CCD Case Validation in RAS FTAs - env.AZURE_CA…"

src/main/resources/roleconfig/role_common.json, src/main/resources/validationrules/privatelaw/privatelaw-case-role-validation-legal-ops.drl, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CaseRolesDroolsTest.java
https://tools.hmcts.net/jira/browse/DTSAM-388
PRL case roles:
| Case role  | Assignee has role |
| ------------- | ------------- |
| allocated-ctsc-caseworker  | ctsc or ctsc-team-leader  |
| allocated-admin-caseworker  | hearing-centre-admin or hearing-centre-team-leader  |
=> DTSAM-388 add new case roles for Private Law

src/main/resources/db/migration/V20240722_366__DTSAM-366_Enable_ALL_WA_SERVICES_CASE_ALLOCATOR_1_0_Prod.sql
[DTSAM-366](https://tools.hmcts.net/jira/browse/DTSAM-366) _"Enable 'all_wa_services_case_allocator_1_0' RAS flag in PROD"_
Enable `all_wa_services_case_allocator_1_0` DB flag in RAS PROD.
```
[ ] Yes
[x] No
```
=> DTSAM-366 Enable all_wa_services_case_allocator_1_0 flag

src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RasFeatureToggleService.java
https://tools.hmcts.net/jira/browse/DTSAM-418
FeatureToggle checks in FTAs should fail when they receive an unexpected response from server
- #2289
- #2293
=> DTSAM-418 update feature toggle code to throw exception if status != 200

build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-446
Move org.apache.poi Version to Var in Gradle
```
[ ] Yes
[x] No
```
=> DTSAM-446 Move org.apache.poi Version to Var in Gradle

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
[DTSAM-516](https://tools.hmcts.net/jira/browse/DTSAM-516) _"role assignments aat failing due to ERROR: cannot execute INSERT in a read-only transaction"_
Resize storage for RAS DB in AAT
```
[ ] Yes
[x] No
```
=> DTSAM-516 Resize storage for RAS DB in AAT

src/main/resources/roleconfig/role_sscs.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/DTSAM-506
Add new OGD role IBCA for SSCS
> NB: This PR is a dependency of hmcts/am-org-role-mapping-service#2084
=> DTSAM-506 add IBCA role config

src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-006/S-088.td.json, src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-009/S-185.td.json, src/functionalTest/resources/features/F-009/S-185_CreationDataForRoleAssignment.td.json, src/functionalTest/resources/features/F-009/S-185_DeleteDataForMultipleRoleAssignments.td.json
https://tools.hmcts.net/jira/browse/DTSAM-574
FTA PR for #2355
=> DTSAM-574 FTA added scenario for v1 & 2 query req with includeLabels

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DTSAM-603
Temporary disable FTAs that use CCD Validation and fix issues
```
[ ] Yes
[x] No
```
=> DTSAM-603 Temporary disable FTAs that use CCD Validation and fix issues

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/resources/features/F-014/S-219.td.json, src/functionalTest/resources/features/F-014/S-220.td.json, src/functionalTest/resources/features/F-015/S-223.td.json, src/functionalTest/resources/features/F-015/S-224.td.json, src/functionalTest/resources/features/F-015/S-225.td.json, src/functionalTest/resources/features/F-015/S-226.td.json, src/functionalTest/resources/features/F-015/S-227.td.json, src/functionalTest/resources/features/F-015/S-228.td.json, src/functionalTest/resources/features/F-015/S-229.td.json
https://tools.hmcts.net/jira/browse/DTSAM-603
- Enable CCD FTA
- Update case id for PRL case role assignments
=> DTSAM-603 PRL FTA update case id

infrastructure/main.tf, infrastructure/variables.tf
=> CME-121: Database monitoring and alerting on AM repositories

infrastructure/main.tf
=> CME-121: remove action group config to test deletions

infrastructure/main.tf
=> CME-121: Provide minimum required config

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RoleAssignmentTestAutomationAdapter.java
[DTSAM-611](https://tools.hmcts.net/jira/browse/DTSAM-611) _"Fix RAS FTA issue with XUI S2S token"_
Refactor S2S token secrets and environment variables used in FTAs.
```
[ ] Yes
[x] No
```
=> DTSAM-611 Fix RAS FTA issue with XUI S2S token

infrastructure/main.tf, infrastructure/variables.tf
=> CME-121 : set thresholds to 10 percent

infrastructure/variables.tf
=> Cme 121 thresholds

infrastructure/variables.tf
=> Cme 121 thresholds desc

infrastructure/main.tf, infrastructure/variables.tf
=> Set CPU, Memory and Storage limits

infrastructure/main.tf
=> Change frequency and window size

infrastructure/main.tf
=> CME-121: Change window size and frequency

infrastructure/variables.tf
=> CME-121: Change thresholds

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DTSAM-633
Temporarily disable the PUBLICLAW case-role FTAs in RAS
```
[ ] Yes
[x] No
```
=> DTSAM-633 Temporarily disable the PUBLICLAW case-role FTAs in RAS

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/SpecificAccessDroolsTest.java
[COT-941](https://tools.hmcts.net/jira/browse/COT-941) _"Update to staff role mappings - Specific access"_
Additional Specific Access Approver unit tests.
> NB: This PR is a patch to #2457.
```
[ ] Yes
[x] No
```
=> COT-941 patch to PR 2457: Additional Specific Access unit tests

charts/am-role-assignment-service/Chart.yaml
=> CME-390: AM Helm OCI update am-role-assignment-service

build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-812
Upgrade fortify
```
[ ] Yes
[ ] No
```
=> DTSAM-812 Upgrade Fortify Client to 1.4.8 AM(ORM/RAS/JBS) repos

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/main/resources/roleconfig/role_civil.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
https://tools.hmcts.net/jira/browse/COT-958
Added new wlu-administrator role
> NB: This PR is a dependency of hmcts/am-org-role-mapping-service#2295.
```
[ ] Yes
[X] No
```
=> COT-958 Added new wlu-admin organisation role config and updated relevant test

Jenkinsfile_CNP, Jenkinsfile_nightly
[DTSAM-875](https://tools.hmcts.net/jira/browse/DTSAM-875) _"Temporary disable FTAs that use CCD Validation and fix issues"_
Temporary disable FTAs that use CCD Validation whilst we fix cases.
```
[ ] Yes
[x] No
```
=> DTSAM-875 Temp disable of FTAs with CCD Validation

config/owasp/suppressions.xml
[DTSAM-976](https://tools.hmcts.net/jira/browse/DTSAM-976) _"Review CVE suppressions after SB3 + DTSPO-23398"_
Adjust CVE suppressions before SB3 + after DTSPO-23398
> NB: The equivilant change for after SB3 is in #2528.
=> DTSAM-976 Review CVE suppressions before SB3 + after DTSPO-23398

src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/main/resources/roleconfig/role_civil.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
[COT-1003](https://tools.hmcts.net/jira/browse/COT-1003) _"Create new rules for new CIVIL Role - WLU Team Leader"_
Add new WLU Team Leader role
```
[ ] Yes
[X] No
```
=> COT-1003 Add new WLU Team Leader role

src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/queryroles/QueryRoleAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/security/IdamRoleServiceTest.java
[CME-56](https://tools.hmcts.net/jira/browse/CME-56) _"Spring Boot 3 Upgrade and Java 21 Upgrade RAS"_
[DTSAM-915](https://tools.hmcts.net/jira/browse/DTSAM-915) _"Additional RAS testing changes triggered by CME-56"_
This is a PATCH PR for #2432. The changes include:
* Re-adjust some unit tests for clarification of behaviour
```
[ ] Yes
[x] No
```
=> DTSAM-915 / CME-56 PATCH - Unit Test adjustments

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/controller/RoleAssignmentIntegrationTest.java, src/main/resources/roleconfig/role_ccd.json, src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/CCDCaseRolesTest.java
https://tools.hmcts.net/jira/browse/DTSAM-1000
Create Barrister case roles in Access-Management
=> DTSAM-1000 Barrister case roles for Private Law 
